In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(mylist)
b = np.array(mymatrix)

In [3]:
type(a)

numpy.ndarray

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np.linspace(1,6,6)

array([1., 2., 3., 4., 5., 6.])

In [10]:
np.random.rand(5,6)

array([[0.22076446, 0.24783088, 0.29037165, 0.32547107, 0.89408618,
        0.19460145],
       [0.4578708 , 0.59840861, 0.51220014, 0.42108657, 0.07271634,
        0.15145711],
       [0.23640645, 0.27954916, 0.86989759, 0.10915178, 0.02425639,
        0.69845405],
       [0.38353269, 0.91600625, 0.67223924, 0.71420504, 0.28784896,
        0.25512159],
       [0.18377792, 0.38874761, 0.78994127, 0.0220054 , 0.31459839,
        0.85914884]])

In [11]:
np.random.randn(5,6)

array([[-0.58852882, -1.69401697,  0.92935885, -1.9113729 , -1.40969543,
        -0.42115173],
       [-0.15002059, -0.35068527, -0.71783327, -0.35219641, -0.1862143 ,
        -0.6785555 ],
       [ 0.61065632,  0.22313323,  2.54900851,  1.28701511,  1.16647363,
         0.31600369],
       [-0.51201692, -0.34136044, -0.07033274, -0.44800153,  1.16792814,
        -0.43664276],
       [-0.49759254,  1.20940582, -0.06911034, -0.14821489,  1.10980457,
        -1.2011138 ]])

In [12]:
np.random.randint(0,56,(5,7))

array([[52, 30, 16, 38,  4,  3, 11],
       [48,  9, 20, 40, 42, 35, 42],
       [10, 17, 42, 40,  1,  1,  5],
       [54, 37, 49, 13, 13,  7,  4],
       [44, 44, 54, 12,  9, 43, 29]])

In [14]:
arr = np.arange(1,11)

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [17]:
bool_arr = arr > 4

In [18]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [19]:
np.count_nonzero(arr[bool_arr])

6

In [20]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = len(dice_rolls[dice_rolls > 2])
total_rolls_over_two

19